### ISSUE TITLE
 ignore dist and types folder

### ISSUE THREAD

**Issue by Jimmysh** [UIUXEngineering/node-typescript-seed#27]
This project is a good job.  I'm trying to create a backend framework with typescript and angular di , I would like to submit some code. Can you ignore dist and types folder? difficult to fork.

**Comment by jerryorta-dev** [comment]
Thank you!

Ignoring `dist` and `types` makes sense. Do you mind submitting a PR?

**Comment by jerryorta-dev** [comment]
Actually, I will do it so you can fork easier.

**Comment by jerryorta-dev** [comment]
done.
