### ISSUE TITLE
can node-typescript-seed support angular e2e test?

### ISSUE THREAD

**Issue by Jimmysh** [UIUXEngineering/node-typescript-seed#31]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x ] feature request
```
node-typescript-seed is very useful help me manage my typescript package and NodeJs project.
I want it can support manage angular library.

Can node-typescript-seed support angular e2e test like ionic project?
https://github.com/driftyco/ionic/blob/master/scripts/gulp/tasks/e2e.dev.ts

gulp e2e.watch is very useful for me.

**Comment by jerryorta-dev** [comment]
If you can implement a PR, I will happily accept it. My support time has dramatically become limited in the past couple of months. 

I started to make an ngModule in this forked project [node-typescript-validate](https://github.com/UIUXEngineering/node-typescript-validate/tree/develop)

in the develop branch. It's not finished,  but I have a start. It's for my job, therefore I am able to spend a little time on it.
